from __future__ import annotations

import os
import shlex
import sys
from pathlib import Path
from typing import Sequence

from .detector import ComfyUIDetectionResult


def generate_launcher_script(
    detection: ComfyUIDetectionResult,
    extra_args: Sequence[str] | str | None = None,
    host: str = "127.0.0.1",
    port: int = 8188,
    output_dir: Path | None = None,
) -> Path:
    """Generate user launcher script (.bat for Windows, .sh for Linux/macOS).

    Contains safely quoted/escaped absolute paths, working directory, and extra arguments.
    Saved to output_dir or comfy_dir.
    """
    if not detection.is_valid or not detection.comfy_dir or not detection.main_py or not detection.interpreter:
        raise ValueError("Cannot generate launcher script for invalid ComfyUI detection result.")

    is_windows = sys.platform == "win32" or os.name == "nt"
    target_dir = output_dir or detection.comfy_dir
    target_dir.mkdir(parents=True, exist_ok=True)

    args_list = ["--listen", host, "--port", str(port)]
    if extra_args:
        if isinstance(extra_args, str):
            extra_tokens = shlex.split(extra_args) if extra_args.strip() else []
        else:
            extra_tokens = list(extra_args)
        args_list.extend(extra_tokens)

    if is_windows:
        script_path = target_dir / "run_comfyui_cmv.bat"
        py_str = f'"{detection.interpreter}"'
        main_str = f'"{detection.main_py}"'
        args_str = " ".join(args_list)

        script_content = (
            "@echo off\r\n"
            "rem Generated by ComfyUI Meta Viewer\r\n"
            f'cd /d "{detection.comfy_dir}"\r\n'
            f'{py_str} {main_str} {args_str} %*\r\n'
        )
    else:
        script_path = target_dir / "run_comfyui_cmv.sh"
        py_str = shlex.quote(str(detection.interpreter))
        main_str = shlex.quote(str(detection.main_py))
        dir_str = shlex.quote(str(detection.comfy_dir))
        args_str = " ".join(shlex.quote(a) for a in args_list)

        script_content = (
            "#!/usr/bin/env bash\n"
            "# Generated by ComfyUI Meta Viewer\n"
            f"cd {dir_str}\n"
            f'{py_str} {main_str} {args_str} "$@"\n'
        )

    script_path.write_text(script_content, encoding="utf-8")
    if not is_windows:
        try:
            os.chmod(script_path, 0o755)
        except OSError:
            pass

    return script_path
